name: Deploy to GitHub Pages

on:
  push:
    branches:
      - Priority  # O la tua branch principale (es. master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.2.0'  # O la versione di Node.js che stai usando

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run ng build pokemon-collection-tracker-app --configuration=production

      - name: Remove unnecessary files
        run: |
          rm -rf dist/pokemon-collection-tracker-app/.git
          rm -rf dist/pokemon-collection-tracker-app/.github
          rm -rf dist/pokemon-collection-tracker-app/src
          rm -rf dist/pokemon-collection-tracker-app/node_modules
          rm -rf dist/pokemon-collection-tracker-app/.angular

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: production  # Branch di destinazione
          folder: dist/pokemon-collection-tracker-app  # Cartella di build
          clean: true # Pulisce la branch prima del deploy
